import { Injectable } from '@nestjs/common';
import PDFDocument = require('pdfkit');
import { InvestigationService } from '../investigation/investigation.service';

// Color palette
const C = {
  dark: '#0F172A',
  text: '#334155',
  gray: '#64748B',
  muted: '#94A3B8',
  light: '#CBD5E1',
  rule: '#E2E8F0',
  red: '#DC2626',
  amber: '#F59E0B',
  orange: '#EA580C',
  green: '#10B981',
  blue: '#3B82F6',
  bg: '#F8FAFC',
};

function titleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}

function sevColor(sev: string): string {
  return sev === 'CRITICAL' ? C.red : sev === 'HIGH' ? C.orange : sev === 'MEDIUM' ? C.amber : C.muted;
}

@Injectable()
export class ReportService {
  constructor(private readonly investigations: InvestigationService) {}

  async generatePdf(investigationId: string): Promise<Buffer> {
    const inv = await this.investigations.findOne(investigationId);
    const relations = await this.investigations.computeRelationsPublic(investigationId);

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margins: { top: 60, bottom: 60, left: 60, right: 60 } });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const W = 475; // usable width
      const companyName = inv.companyName || inv.query;
      const findings = inv.findings || [];
      const entities = inv.entities || {};
      const matches = inv.matches || [];
      const uboChains = inv.uboChains || [];
      const score = inv.riskScore ?? 0;
      const counts = inv.counts || {};

      // Build relation sets
      const targetIds = new Set<string>();
      const directorIds = new Set<string>();
      for (const [id, rel] of relations) {
        if (rel === 'Target') targetIds.add(id);
        if (rel === 'Director' || rel === 'PSC/Owner') directorIds.add(id);
      }
      for (const group of ['company', 'person', 'address']) {
        for (const e of (entities as any)[group] || []) {
          if (targetIds.has(e.id) && e.entityId) targetIds.add(e.entityId);
          if (directorIds.has(e.id) && e.entityId) directorIds.add(e.entityId);
        }
      }

      const targetFindings = findings.filter((f: any) => (f.affectedEntities || []).some((id: string) => targetIds.has(id)));
      const directorFindings = findings.filter((f: any) =>
        !(f.affectedEntities || []).some((id: string) => targetIds.has(id)) &&
        (f.affectedEntities || []).some((id: string) => directorIds.has(id)),
      );
      const networkFindings = findings.filter((f: any) =>
        !(f.affectedEntities || []).some((id: string) => targetIds.has(id)) &&
        !(f.affectedEntities || []).some((id: string) => directorIds.has(id)),
      );

      const targetEntity = (entities.company || []).find((c: any) => targetIds.has(c.id));
      const meta = targetEntity?.metadata || {};

      // =============================================
      // PAGE 1 — COVER
      // =============================================
      doc.moveDown(6);
      doc.fontSize(9).fillColor(C.muted).text('TRACEGRAPH', { characterSpacing: 4, align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor(C.gray).text('Corporate Intelligence Report', { align: 'center' });
      doc.moveDown(4);
      doc.fontSize(32).fillColor(C.dark).text(companyName, { align: 'center' });
      doc.moveDown(0.8);
      const coverDetails: string[] = [];
      if (inv.rootCompanyNumber) coverDetails.push(`Company ${inv.rootCompanyNumber}`);
      if (meta.jurisdiction) coverDetails.push(meta.jurisdiction.replace('-', ' '));
      doc.fontSize(11).fillColor(C.gray).text(coverDetails.join('  ·  '), { align: 'center' });
      doc.moveDown(3);

      // Risk score on cover
      const scoreColor = score >= 75 ? C.red : score >= 50 ? C.orange : score >= 25 ? C.amber : C.green;
      doc.fontSize(56).fillColor(scoreColor).text(`${score}`, { align: 'center' });
      doc.fontSize(12).fillColor(C.muted).text('/ 100  RISK SCORE', { align: 'center' });
      doc.moveDown(1);
      const tierLabel = inv.tier === 'DEEP' ? 'Deep Investigation' : inv.tier === 'QUICK' ? 'Quick Scan' : 'Standard Investigation';
      doc.fontSize(9).fillColor(C.gray).text(tierLabel, { align: 'center' });
      doc.moveDown(6);

      doc.fontSize(8).fillColor(C.muted).text('CONFIDENTIAL', { align: 'center', characterSpacing: 2 });
      doc.moveDown(3);
      doc.fontSize(8).fillColor(C.light).text(
        `Generated ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}  ·  Report ID: ${investigationId.slice(0, 8)}`,
        { align: 'center' },
      );
      doc.fontSize(8).fillColor(C.light).text('Generated by TraceGraph', { align: 'center' });

      // =============================================
      // PAGE 2 — EXECUTIVE SUMMARY
      // =============================================
      doc.addPage();
      this.pageHeader(doc, companyName);

      this.sectionTitle(doc, 'Executive Summary');
      doc.moveDown(0.5);

      // Plain English summary paragraph
      const age = meta.incorporationDate ? Math.floor((Date.now() - new Date(meta.incorporationDate).getTime()) / (365.25 * 24 * 60 * 60 * 1000)) : null;
      const leadership = (entities.person || []).filter((p: any) => {
        const r = relations.get(p.id); return r === 'Director' || r === 'PSC/Owner';
      });
      const summaryParts: string[] = [];
      summaryParts.push(`${companyName} is ${meta.status === 'active' ? 'an active' : 'a ' + (meta.status || 'registered')} ${meta.companyType || 'company'}`);
      if (age !== null) summaryParts.push(`incorporated ${age} years ago`);
      summaryParts.push(`with ${leadership.length} directors/PSCs and a network of ${(counts.companies || 0).toLocaleString()} connected companies.`);
      if (targetFindings.length > 0) {
        summaryParts.push(`${targetFindings.length} risk signals were detected directly on the target company.`);
      } else {
        summaryParts.push('No risk signals were detected directly on the target company.');
      }
      if (matches.length > 0) summaryParts.push(`${matches.length} cross-source match${matches.length > 1 ? 'es' : ''} found against sanctions or offshore databases.`);

      doc.fontSize(11).fillColor(C.text).text(summaryParts.join(' '), { lineGap: 3 });
      doc.moveDown(1.5);

      // Verdict box
      const verdict = score >= 75 ? { label: 'DO NOT PROCEED WITHOUT LEGAL REVIEW', color: C.red }
        : score >= 50 ? { label: 'ENHANCED DUE DILIGENCE RECOMMENDED', color: C.orange }
        : score >= 25 ? { label: 'PROCEED WITH CAUTION', color: C.amber }
        : { label: 'PROCEED', color: C.green };

      const vY = doc.y;
      doc.rect(60, vY, W, 36).fill(verdict.color);
      doc.fontSize(11).fillColor('#FFFFFF').text(verdict.label, 60, vY + 12, { width: W, align: 'center' });
      doc.y = vY + 48;
      doc.moveDown(1.5);

      // Key stats row
      this.statRow(doc, [
        { label: 'ENTITIES SCANNED', value: String((counts.companies || 0) + (counts.people || 0) + (counts.addresses || 0)) },
        { label: 'CONNECTIONS', value: String(counts.edges || 0) },
        { label: 'FINDINGS', value: String(findings.length) },
        { label: 'SANCTIONS MATCHES', value: String(matches.length) },
      ]);
      doc.moveDown(2);

      // Target company profile summary
      this.sectionTitle(doc, 'Company Profile');
      doc.moveDown(0.3);
      const fields: [string, string][] = [];
      if (meta.status) fields.push(['Status', titleCase(meta.status)]);
      if (meta.companyType) fields.push(['Type', titleCase(meta.companyType)]);
      if (meta.incorporationDate) fields.push(['Incorporated', meta.incorporationDate]);
      if (meta.accountsType) fields.push(['Accounts', titleCase(meta.accountsType)]);
      if (meta.jurisdiction) fields.push(['Jurisdiction', titleCase(meta.jurisdiction.replace(/-/g, ' '))]);
      if (meta.filingHealth) fields.push(['Filing health', `${meta.filingHealth.band} (${meta.filingHealth.score}/100)`]);
      if (meta.shellCompanyScore) fields.push(['Shell risk', `${meta.shellCompanyScore.risk} (${meta.shellCompanyScore.score}/100)`]);
      if (meta.ownershipOpacity) fields.push(['Ownership transparency', `${meta.ownershipOpacity.band} (${meta.ownershipOpacity.score}/100)`]);
      for (const [label, value] of fields) {
        this.fieldRow(doc, label, value);
      }

      // =============================================
      // PAGE 3 — OWNERSHIP
      // =============================================
      doc.addPage();
      this.pageHeader(doc, companyName);
      this.sectionTitle(doc, 'Ownership Structure');
      doc.moveDown(0.5);

      if (uboChains.length === 0) {
        doc.fontSize(10).fillColor(C.gray).text('No UBO chains resolved. Ownership data may be limited.');
      } else {
        for (const chain of uboChains.slice(0, 3)) {
          this.checkPageBreak(doc, 120);
          const path = chain.path || [];
          const ubo = path[0];

          // UBO header
          doc.fontSize(12).fillColor(C.dark).text(`Ultimate Beneficial Owner: ${ubo?.name || 'Unknown'}`);
          if (chain.effectiveOwnershipPct != null) {
            doc.fontSize(9).fillColor(C.gray).text(`${chain.effectiveOwnershipPct}% effective ownership`);
          }
          doc.moveDown(1);

          // Ownership chain — each node gets a clear row with box-style layout
          for (let i = 0; i < path.length; i++) {
            const node = path[i];
            const indent = i * 30;
            const x = 70 + indent;

            // Connector line
            if (i > 0) {
              doc.fontSize(9).fillColor(C.light).text('|', x - 12, doc.y);
              doc.moveDown(0.2);
            }

            // Node name (bold for person, regular for company)
            const isPerson = node.kind === 'person';
            const badge = isPerson ? 'Person' : 'Company';
            doc.fontSize(10).fillColor(C.dark).text(node.name, x);

            // Details on next line
            const details: string[] = [badge];
            if (node.ownershipPct) details.push(`${node.ownershipPct}% ownership`);
            if (node.jurisdiction) details.push(node.jurisdiction);
            if (node.companyNumber) details.push(node.companyNumber);
            doc.fontSize(8).fillColor(C.gray).text(details.join('  ·  '), x);

            doc.moveDown(0.6);
          }

          doc.moveDown(0.5);
          if (chain.terminationReason) {
            doc.fontSize(8).fillColor(C.muted).text(`Chain resolved: ${chain.terminationReason}`);
          }
          doc.moveDown(2);
        }
      }

      // =============================================
      // PAGE 4 — LEADERSHIP
      // =============================================
      doc.addPage();
      this.pageHeader(doc, companyName);
      this.sectionTitle(doc, 'Leadership Assessment');
      doc.moveDown(0.5);

      if (leadership.length === 0) {
        doc.fontSize(10).fillColor(C.gray).text('No direct directors or PSCs found in the data.');
      } else {
        // Table header
        doc.fontSize(8).fillColor(C.muted);
        doc.text('NAME', 60, doc.y, { continued: true, width: 160 });
        doc.text('ROLE', 220, doc.y, { continued: true, width: 60 });
        doc.text('NATIONALITY', 280, doc.y, { continued: true, width: 70 });
        doc.text('TRACK RECORD', 350, doc.y, { continued: true, width: 100 });
        doc.text('RISK', 450, doc.y, { width: 85 });
        doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor(C.rule).stroke();
        doc.moveDown(0.3);

        for (const person of leadership) {
          this.checkPageBreak(doc, 30);
          const pmeta = person.metadata || {};
          const dp = pmeta.directorProfile || {};
          const rel = relations.get(person.id) || 'Director';
          const role = rel === 'PSC/Owner' ? 'PSC' : 'Director';
          const risk = dp.risk && dp.risk !== 'NORMAL' ? dp.risk.replace(/_/g, ' ') : '-';
          const riskColor = (dp.risk === 'NOMINEE_PATTERN' || dp.risk === 'FORMATION_AGENT') ? C.red : C.text;
          const track = dp.totalAppointments ? `${dp.active || 0} active, ${dp.dissolved || 0} dissolved` : '-';

          const y = doc.y;
          doc.fontSize(9).fillColor(C.dark).text(person.label, 60, y, { width: 160 });
          doc.fontSize(8).fillColor(role === 'PSC' ? C.amber : C.gray).text(role, 220, y, { width: 60 });
          doc.fontSize(8).fillColor(C.text).text(pmeta.nationality || '-', 280, y, { width: 70 });
          doc.fontSize(8).fillColor(C.text).text(track, 350, y, { width: 100 });
          doc.fontSize(8).fillColor(riskColor).text(risk, 450, y, { width: 85 });
          doc.y = Math.max(doc.y, y + 14);

          // Sanctions match indicator
          if (person.matches?.length > 0) {
            doc.fontSize(8).fillColor(C.red).text(
              `  SANCTIONS MATCH: ${person.matches.map((m: any) => `${m.reasons?.matchedName || m.matchedEntityId} (${m.confidence}%)`).join(', ')}`,
              60,
            );
          }
          doc.moveDown(0.2);
        }
      }

      // =============================================
      // PAGE 5+ — FINDINGS
      // =============================================
      doc.addPage();
      this.pageHeader(doc, companyName);
      this.sectionTitle(doc, `Findings on ${companyName}`);
      doc.moveDown(0.5);

      if (targetFindings.length === 0) {
        doc.fontSize(10).fillColor(C.green).text(`No risk signals detected directly on ${companyName}.`);
      } else {
        doc.fontSize(10).fillColor(C.text).text(`${targetFindings.length} finding${targetFindings.length > 1 ? 's' : ''} directly affecting the target company:`);
        doc.moveDown(0.5);
        this.renderFindings(doc, targetFindings.slice(0, 15));
        if (targetFindings.length > 15) {
          doc.fontSize(8).fillColor(C.muted).text(`  + ${targetFindings.length - 15} more findings (see full report online)`);
        }
      }
      doc.moveDown(1.5);

      // Director findings
      this.checkPageBreak(doc, 80);
      this.sectionTitle(doc, 'Findings on Directors');
      doc.moveDown(0.5);
      if (directorFindings.length === 0) {
        doc.fontSize(10).fillColor(C.green).text('No risk signals on target company directors.');
      } else {
        doc.fontSize(10).fillColor(C.text).text(`${directorFindings.length} finding${directorFindings.length > 1 ? 's' : ''} about directors and PSCs:`);
        doc.moveDown(0.5);
        this.renderFindings(doc, directorFindings.slice(0, 15));
        if (directorFindings.length > 15) {
          doc.fontSize(8).fillColor(C.muted).text(`  ...and ${directorFindings.length - 15} more director findings`);
        }
      }
      doc.moveDown(1.5);

      // Network findings summary
      this.checkPageBreak(doc, 80);
      this.sectionTitle(doc, 'Network Findings Summary');
      doc.moveDown(0.5);
      if (networkFindings.length === 0) {
        doc.fontSize(10).fillColor(C.green).text('No findings in the wider network.');
      } else {
        const nCrit = networkFindings.filter((f: any) => f.severity === 'CRITICAL').length;
        const nHigh = networkFindings.filter((f: any) => f.severity === 'HIGH').length;
        doc.fontSize(10).fillColor(C.text).text(
          `${networkFindings.length.toLocaleString()} findings in the wider network (${nCrit} critical, ${nHigh} high). Top 5:`,
        );
        doc.moveDown(0.5);
        const topNet = [...networkFindings].sort((a: any, b: any) => {
          const o: Record<string, number> = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
          return (o[a.severity] ?? 3) - (o[b.severity] ?? 3);
        });
        this.renderFindings(doc, topNet.slice(0, 5));
      }

      // Cross-source matches
      if (matches.length > 0) {
        doc.moveDown(1.5);
        this.checkPageBreak(doc, 80);
        this.sectionTitle(doc, 'Cross-Source Matches');
        doc.moveDown(0.5);
        for (const m of matches.slice(0, 10)) {
          this.checkPageBreak(doc, 30);
          const src = m.source === 'opensanctions' ? 'OpenSanctions' : 'ICIJ OffshoreLeaks';
          doc.fontSize(10).fillColor(C.dark).text(m.reasons?.matchedName || m.matchedEntityId, { continued: true });
          doc.fontSize(9).fillColor(m.confidence >= 75 ? C.red : C.amber).text(`  ${m.confidence}%`, { continued: true });
          doc.fontSize(9).fillColor(C.gray).text(`  ${src}`);
          doc.moveDown(0.3);
        }
      }

      // =============================================
      // FINAL PAGE — METHODOLOGY & SOURCES
      // =============================================
      doc.addPage();
      this.pageHeader(doc, companyName);
      this.sectionTitle(doc, 'Methodology & Sources');
      doc.moveDown(0.5);

      doc.fontSize(10).fillColor(C.text).text(
        'This report was generated using publicly available data from the following sources:',
        { lineGap: 2 },
      );
      doc.moveDown(0.5);

      const sources = [
        ['UK Companies House API', 'Company profiles, officers, PSCs, filing history, charges, registered offices'],
        ['OpenSanctions', '4.1 million sanctions, PEP, and watchlist entities from 100+ global sources'],
        ['ICIJ OffshoreLeaks', '770,000+ offshore entities, officers, and intermediaries from leaked databases'],
      ];
      for (const [name, desc] of sources) {
        doc.fontSize(10).fillColor(C.dark).text(name, { continued: true });
        doc.fontSize(9).fillColor(C.gray).text(`  -  ${desc}`);
        doc.moveDown(0.3);
      }
      doc.moveDown(1.5);

      this.sectionTitle(doc, 'Risk Scoring Methodology');
      doc.moveDown(0.5);
      doc.fontSize(9).fillColor(C.text).text(
        'The risk score (0-100) is computed from 30+ automated detectors analyzing: shell company indicators ' +
        '(micro-entity accounts, virtual office addresses, rapid dissolutions, high director turnover), ' +
        'director network patterns (nominee patterns, formation agents, cross-directorship conflicts), ' +
        'filing health (late accounts, dormant cycling, phoenix patterns), ownership transparency ' +
        '(corporate PSCs, offshore jurisdictions, missing UBO chains), and sanctions proximity ' +
        '(shortest path to any matched entity in sanctions or offshore databases).',
        { lineGap: 2 },
      );
      doc.moveDown(1.5);

      doc.fontSize(9).fillColor(C.text).text('Score interpretation:', { lineGap: 2 });
      doc.fontSize(9).fillColor(C.green).text('0-24: Low risk', { continued: true });
      doc.fillColor(C.text).text('  -  No significant concerns identified');
      doc.fontSize(9).fillColor(C.amber).text('25-49: Elevated', { continued: true });
      doc.fillColor(C.text).text('  -  Some signals warrant review');
      doc.fontSize(9).fillColor(C.orange).text('50-74: High', { continued: true });
      doc.fillColor(C.text).text('  -  Enhanced due diligence recommended');
      doc.fontSize(9).fillColor(C.red).text('75-100: Critical', { continued: true });
      doc.fillColor(C.text).text('  -  Do not proceed without legal review');
      doc.moveDown(2);

      // Disclaimer
      doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor(C.rule).stroke();
      doc.moveDown(0.5);
      doc.fontSize(8).fillColor(C.muted).text(
        'DISCLAIMER: This report is generated from publicly available data and automated analysis. ' +
        'It does not constitute legal, financial, or professional advice. The risk score is indicative ' +
        'and should not be the sole basis for business decisions. Independent verification of all ' +
        'findings is recommended before taking any action.',
        { lineGap: 2 },
      );
      doc.moveDown(1);
      doc.fontSize(8).fillColor(C.light).text(
        `Report generated ${new Date().toISOString().slice(0, 10)}  ·  Investigation ${investigationId.slice(0, 8)}  ·  TraceGraph v1.0`,
      );

      // Add page numbers
      const pages = doc.bufferedPageRange();
      for (let i = pages.start; i < pages.start + pages.count; i++) {
        doc.switchToPage(i);
        doc.fontSize(7).fillColor(C.light).text(
          `${i + 1}`,
          0, doc.page.height - 40,
          { width: doc.page.width, align: 'center' },
        );
        if (i > 0) {
          doc.fontSize(7).fillColor(C.light).text(
            'TraceGraph Confidential',
            60, doc.page.height - 40,
          );
        }
      }

      doc.end();
    });
  }

  private renderFindings(doc: any, findings: any[]) {
    const SEV_ORDER: Record<string, number> = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
    const sorted = [...findings].sort((a, b) => (SEV_ORDER[a.severity] ?? 3) - (SEV_ORDER[b.severity] ?? 3));
    for (let fi = 0; fi < sorted.length; fi++) {
      const f = sorted[fi];
      this.checkPageBreak(doc, 80);

      // Severity badge + title on one line
      const sColor = sevColor(f.severity);
      doc.fontSize(8).fillColor(sColor).text(f.severity, { continued: true });
      doc.fontSize(10).fillColor(C.dark).text(`  ${f.title}`);
      doc.moveDown(0.3);

      // Description — truncate to 2 lines max
      const desc = (f.description || '').slice(0, 200) + (f.description?.length > 200 ? '...' : '');
      doc.fontSize(9).fillColor(C.text).text(desc, { lineGap: 2 });
      doc.moveDown(0.3);

      // Business impact (condensed)
      if (f.businessImpact) {
        const impact = f.businessImpact.slice(0, 150) + (f.businessImpact.length > 150 ? '...' : '');
        doc.fontSize(8).fillColor(C.gray).text(`Impact: ${impact}`);
      }

      // Verification links inline
      if (f.verificationLinks?.length > 0) {
        const linkTexts = f.verificationLinks.map((l: any) => l.label).join('  |  ');
        doc.fontSize(8).fillColor(C.blue).text(linkTexts);
      }

      // Divider between findings
      doc.moveDown(0.8);
      if (fi < sorted.length - 1) {
        doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor('#F1F5F9').stroke();
        doc.moveDown(0.8);
      }
    }
  }

  private pageHeader(doc: any, companyName: string) {
    doc.fontSize(7).fillColor(C.light).text(companyName, 60, 30);
    doc.fontSize(7).fillColor(C.light).text('TraceGraph Intelligence Report', 60, 30, { width: 475, align: 'right' });
    doc.y = 60;
  }

  private sectionTitle(doc: any, title: string) {
    doc.fontSize(8).fillColor(C.muted).text(title.toUpperCase(), { characterSpacing: 1.5 });
    doc.moveTo(60, doc.y + 2).lineTo(535, doc.y + 2).strokeColor(C.rule).stroke();
    doc.moveDown(0.3);
  }

  private fieldRow(doc: any, label: string, value: string) {
    const y = doc.y;
    doc.fontSize(9).fillColor(C.gray).text(label, 60, y, { width: 150 });
    doc.fontSize(9).fillColor(C.dark).text(value, 210, y, { width: 325 });
    doc.y = Math.max(doc.y, y + 14);
  }

  private statRow(doc: any, stats: Array<{ label: string; value: string }>) {
    const colW = 475 / stats.length;
    const y = doc.y;
    for (let i = 0; i < stats.length; i++) {
      const x = 60 + i * colW;
      doc.fontSize(14).fillColor(C.dark).text(stats[i].value, x, y, { width: colW });
      doc.fontSize(7).fillColor(C.muted).text(stats[i].label, x, y + 18, { width: colW, characterSpacing: 0.5 });
    }
    doc.y = y + 34;
  }

  private checkPageBreak(doc: any, needed: number) {
    if (doc.y + needed > doc.page.height - 60) {
      doc.addPage();
      this.pageHeader(doc, '');
    }
  }
}
